CREATE TABLE "C##RCUSER"."JSON_TRANS"(
    "ID" NUMBER(8,0) NOT NULL ENABLE,
    "TRANS_MSG" CLOB,
    CONSTRAINT "CHECK_JSON" CHECK (trans_msg is json) ENABLE,
    PRIMARY KEY ("ID") USING INDEX ENABLE,
    SUPPLEMENTAL LOG DATA (ALL) COLUMNS)
