CREATE TABLE "ASEDBUSR"."DOCBESTPARAMATTR"
(	"PKEY" NUMBER(12,0) NOT NULL ENABLE,
	"BOID" VARCHAR2(40 CHAR) NOT NULL ENABLE,
	"METABO" NUMBER(12,0) NOT NULL ENABLE,
	"LASTUPDATE" TIMESTAMP (9) NOT NULL ENABLE,
	"PROCESSID" VARCHAR2(40 CHAR) NOT NULL ENABLE,
	"ROWCOMMENT" VARCHAR2(15 CHAR),
	"CREATEDUSER" VARCHAR2(40 CHAR) NOT NULL ENABLE,
	"REPLACED" TIMESTAMP (9) NOT NULL ENABLE,
	"REPLACEDUSER" VARCHAR2(40 CHAR),
	"ARCHIVETAG" VARCHAR2(40 CHAR),
	"GUELTAB" DATE NOT NULL ENABLE,
	"GUELTBIS" DATE NOT NULL ENABLE,
	"ITSPARAMATTRDEF" VARCHAR2(40 CHAR) NOT NULL ENABLE,
	"CODEVALUE" VARCHAR2(40 CHAR),
	"ITSBOVALUE" VARCHAR2(40 CHAR),
	"CLSBOVALUE" NUMBER(12,0),
	"INTVALUE" NUMBER(12,0),
	"DECVALUE" NUMBER(18,6),
	"TEXTVALUE" VARCHAR2(4000 CHAR),
	"DATEVALUE" DATE,
	"ITSDOCBESTELLUNG" VARCHAR2(40 CHAR) NOT NULL ENABLE,
	"MDBID" VARCHAR2(255 CHAR),
	"BIGTEXTVALUE" CLOB,
	"CK_CODEVALUE" VARCHAR2(40 CHAR),
	 CONSTRAINT "PK500332" PRIMARY KEY ("PKEY")
  USING INDEX PCTFREE 10 INITRANS 80 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ASEDBUSR_DAT"  ENABLE,
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 40 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ASEDBUSR_DAT"
 LOB ("BIGTEXTVALUE") STORE AS SECUREFILE (
  TABLESPACE "ASEDBUSR_DAT" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
