CREATE TABLE DWH_INT_DBT.sensors_raw (
  SOURCE                 VARCHAR2(50),
  EVENTTS                VARCHAR2(30))
  STORAGE (
    BUFFER_POOL      DEFAULT
    FLASH_CACHE      DEFAULT
    CELL_FLASH_CACHE DEFAULT)
  NOCOMPRESS
  NOCACHE
  RESULT_CACHE (MODE DEFAULT)
  NOPARALLEL
  NOMONITORING
