Feature: File pattern is required

  @err0007
  Scenario Outline: err0007
    Given err0007.<pUnique> input file <pInputFile>
    * err0007.<pUnique> template <pTemplate>
    * err0007.<pUnique> templates <pTemplates>
    * err0007.<pUnique> single multi value <pSinti>
    * err0007.<pUnique> path <pPath>
    * err0007.<pUnique> file <pFile>
    * err0007.<pUnique> var <pVar>
    * err0007.<pUnique> vars <pVars>
    When err0007.<pUnique> the values are passed into Cimerant
    Then err0007.<pUnique> error is thrown

    Examples:
      | pUnique | pInputFile | pTemplate  | pTemplates  | pSinti   | pPath  | pFile | pVar   | pVars       |
      | 1999    | "i"        | "t"        | ""          | "multi"  | ""     | ""    | ""     | ""          |
      | 2000    | "i"        | "t"        | ""          | "multi"  | ""     | ""    | ""     | "variables" |
      | 2001    | "i"        | "t"        | ""          | "multi"  | ""     | ""    | ""     | "x"         |
      | 2002    | "i"        | "t"        | ""          | "multi"  | ""     | ""    | "keys" | ""          |
      | 2003    | "i"        | "t"        | ""          | "multi"  | ""     | ""    | "keys" | "variables" |
      | 2004    | "i"        | "t"        | ""          | "multi"  | ""     | ""    | "keys" | "x"         |
      | 2017    | "i"        | "t"        | ""          | "multi"  | "p"    | ""    | ""     | ""          |
      | 2018    | "i"        | "t"        | ""          | "multi"  | "p"    | ""    | ""     | "variables" |
      | 2019    | "i"        | "t"        | ""          | "multi"  | "p"    | ""    | ""     | "x"         |
      | 2020    | "i"        | "t"        | ""          | "multi"  | "p"    | ""    | "keys" | ""          |
      | 2021    | "i"        | "t"        | ""          | "multi"  | "p"    | ""    | "keys" | "variables" |
      | 2022    | "i"        | "t"        | ""          | "multi"  | "p"    | ""    | "keys" | "x"         |
      | 2035    | "i"        | "t"        | ""          | "multi"  | "path" | ""    | ""     | ""          |
      | 2036    | "i"        | "t"        | ""          | "multi"  | "path" | ""    | ""     | "variables" |
      | 2037    | "i"        | "t"        | ""          | "multi"  | "path" | ""    | ""     | "x"         |
      | 2038    | "i"        | "t"        | ""          | "multi"  | "path" | ""    | "keys" | ""          |
      | 2039    | "i"        | "t"        | ""          | "multi"  | "path" | ""    | "keys" | "variables" |
      | 2040    | "i"        | "t"        | ""          | "multi"  | "path" | ""    | "keys" | "x"         |
      | 2053    | "i"        | "t"        | ""          | "single" | ""     | ""    | ""     | ""          |
      | 2054    | "i"        | "t"        | ""          | "single" | ""     | ""    | ""     | "variables" |
      | 2055    | "i"        | "t"        | ""          | "single" | ""     | ""    | ""     | "x"         |
      | 2056    | "i"        | "t"        | ""          | "single" | ""     | ""    | "keys" | ""          |
      | 2057    | "i"        | "t"        | ""          | "single" | ""     | ""    | "keys" | "variables" |
      | 2058    | "i"        | "t"        | ""          | "single" | ""     | ""    | "keys" | "x"         |
      | 2071    | "i"        | "t"        | ""          | "single" | "p"    | ""    | ""     | ""          |
      | 2072    | "i"        | "t"        | ""          | "single" | "p"    | ""    | ""     | "variables" |
      | 2073    | "i"        | "t"        | ""          | "single" | "p"    | ""    | ""     | "x"         |
      | 2074    | "i"        | "t"        | ""          | "single" | "p"    | ""    | "keys" | ""          |
      | 2075    | "i"        | "t"        | ""          | "single" | "p"    | ""    | "keys" | "variables" |
      | 2076    | "i"        | "t"        | ""          | "single" | "p"    | ""    | "keys" | "x"         |
      | 2089    | "i"        | "t"        | ""          | "single" | "path" | ""    | ""     | ""          |
      | 2090    | "i"        | "t"        | ""          | "single" | "path" | ""    | ""     | "variables" |
      | 2091    | "i"        | "t"        | ""          | "single" | "path" | ""    | ""     | "x"         |
      | 2092    | "i"        | "t"        | ""          | "single" | "path" | ""    | "keys" | ""          |
      | 2093    | "i"        | "t"        | ""          | "single" | "path" | ""    | "keys" | "variables" |
      | 2094    | "i"        | "t"        | ""          | "single" | "path" | ""    | "keys" | "x"         |
      | 2161    | "i"        | "t"        | "l"         | "multi"  | ""     | ""    | ""     | ""          |
      | 2162    | "i"        | "t"        | "l"         | "multi"  | ""     | ""    | ""     | "variables" |
      | 2163    | "i"        | "t"        | "l"         | "multi"  | ""     | ""    | ""     | "x"         |
      | 2164    | "i"        | "t"        | "l"         | "multi"  | ""     | ""    | "keys" | ""          |
      | 2165    | "i"        | "t"        | "l"         | "multi"  | ""     | ""    | "keys" | "variables" |
      | 2166    | "i"        | "t"        | "l"         | "multi"  | ""     | ""    | "keys" | "x"         |
      | 2179    | "i"        | "t"        | "l"         | "multi"  | "p"    | ""    | ""     | ""          |
      | 2180    | "i"        | "t"        | "l"         | "multi"  | "p"    | ""    | ""     | "variables" |
      | 2181    | "i"        | "t"        | "l"         | "multi"  | "p"    | ""    | ""     | "x"         |
      | 2182    | "i"        | "t"        | "l"         | "multi"  | "p"    | ""    | "keys" | ""          |
      | 2183    | "i"        | "t"        | "l"         | "multi"  | "p"    | ""    | "keys" | "variables" |
      | 2184    | "i"        | "t"        | "l"         | "multi"  | "p"    | ""    | "keys" | "x"         |
      | 2197    | "i"        | "t"        | "l"         | "multi"  | "path" | ""    | ""     | ""          |
      | 2198    | "i"        | "t"        | "l"         | "multi"  | "path" | ""    | ""     | "variables" |
      | 2199    | "i"        | "t"        | "l"         | "multi"  | "path" | ""    | ""     | "x"         |
      | 2200    | "i"        | "t"        | "l"         | "multi"  | "path" | ""    | "keys" | ""          |
      | 2201    | "i"        | "t"        | "l"         | "multi"  | "path" | ""    | "keys" | "variables" |
      | 2202    | "i"        | "t"        | "l"         | "multi"  | "path" | ""    | "keys" | "x"         |
      | 2215    | "i"        | "t"        | "l"         | "single" | ""     | ""    | ""     | ""          |
      | 2216    | "i"        | "t"        | "l"         | "single" | ""     | ""    | ""     | "variables" |
      | 2217    | "i"        | "t"        | "l"         | "single" | ""     | ""    | ""     | "x"         |
      | 2218    | "i"        | "t"        | "l"         | "single" | ""     | ""    | "keys" | ""          |
      | 2219    | "i"        | "t"        | "l"         | "single" | ""     | ""    | "keys" | "variables" |
      | 2220    | "i"        | "t"        | "l"         | "single" | ""     | ""    | "keys" | "x"         |
      | 2233    | "i"        | "t"        | "l"         | "single" | "p"    | ""    | ""     | ""          |
      | 2234    | "i"        | "t"        | "l"         | "single" | "p"    | ""    | ""     | "variables" |
      | 2235    | "i"        | "t"        | "l"         | "single" | "p"    | ""    | ""     | "x"         |
      | 2236    | "i"        | "t"        | "l"         | "single" | "p"    | ""    | "keys" | ""          |
      | 2237    | "i"        | "t"        | "l"         | "single" | "p"    | ""    | "keys" | "variables" |
      | 2238    | "i"        | "t"        | "l"         | "single" | "p"    | ""    | "keys" | "x"         |
      | 2251    | "i"        | "t"        | "l"         | "single" | "path" | ""    | ""     | ""          |
      | 2252    | "i"        | "t"        | "l"         | "single" | "path" | ""    | ""     | "variables" |
      | 2253    | "i"        | "t"        | "l"         | "single" | "path" | ""    | ""     | "x"         |
      | 2254    | "i"        | "t"        | "l"         | "single" | "path" | ""    | "keys" | ""          |
      | 2255    | "i"        | "t"        | "l"         | "single" | "path" | ""    | "keys" | "variables" |
      | 2256    | "i"        | "t"        | "l"         | "single" | "path" | ""    | "keys" | "x"         |
      | 2323    | "i"        | "t"        | "templates" | "multi"  | ""     | ""    | ""     | ""          |
      | 2324    | "i"        | "t"        | "templates" | "multi"  | ""     | ""    | ""     | "variables" |
      | 2325    | "i"        | "t"        | "templates" | "multi"  | ""     | ""    | ""     | "x"         |
      | 2326    | "i"        | "t"        | "templates" | "multi"  | ""     | ""    | "keys" | ""          |
      | 2327    | "i"        | "t"        | "templates" | "multi"  | ""     | ""    | "keys" | "variables" |
      | 2328    | "i"        | "t"        | "templates" | "multi"  | ""     | ""    | "keys" | "x"         |
      | 2341    | "i"        | "t"        | "templates" | "multi"  | "p"    | ""    | ""     | ""          |
      | 2342    | "i"        | "t"        | "templates" | "multi"  | "p"    | ""    | ""     | "variables" |
      | 2343    | "i"        | "t"        | "templates" | "multi"  | "p"    | ""    | ""     | "x"         |
      | 2344    | "i"        | "t"        | "templates" | "multi"  | "p"    | ""    | "keys" | ""          |
      | 2345    | "i"        | "t"        | "templates" | "multi"  | "p"    | ""    | "keys" | "variables" |
      | 2346    | "i"        | "t"        | "templates" | "multi"  | "p"    | ""    | "keys" | "x"         |
      | 2359    | "i"        | "t"        | "templates" | "multi"  | "path" | ""    | ""     | ""          |
      | 2360    | "i"        | "t"        | "templates" | "multi"  | "path" | ""    | ""     | "variables" |
      | 2361    | "i"        | "t"        | "templates" | "multi"  | "path" | ""    | ""     | "x"         |
      | 2362    | "i"        | "t"        | "templates" | "multi"  | "path" | ""    | "keys" | ""          |
      | 2363    | "i"        | "t"        | "templates" | "multi"  | "path" | ""    | "keys" | "variables" |
      | 2364    | "i"        | "t"        | "templates" | "multi"  | "path" | ""    | "keys" | "x"         |
      | 2377    | "i"        | "t"        | "templates" | "single" | ""     | ""    | ""     | ""          |
      | 2378    | "i"        | "t"        | "templates" | "single" | ""     | ""    | ""     | "variables" |
      | 2379    | "i"        | "t"        | "templates" | "single" | ""     | ""    | ""     | "x"         |
      | 2380    | "i"        | "t"        | "templates" | "single" | ""     | ""    | "keys" | ""          |
      | 2381    | "i"        | "t"        | "templates" | "single" | ""     | ""    | "keys" | "variables" |
      | 2382    | "i"        | "t"        | "templates" | "single" | ""     | ""    | "keys" | "x"         |
      | 2395    | "i"        | "t"        | "templates" | "single" | "p"    | ""    | ""     | ""          |
      | 2396    | "i"        | "t"        | "templates" | "single" | "p"    | ""    | ""     | "variables" |
      | 2397    | "i"        | "t"        | "templates" | "single" | "p"    | ""    | ""     | "x"         |
      | 2398    | "i"        | "t"        | "templates" | "single" | "p"    | ""    | "keys" | ""          |
      | 2399    | "i"        | "t"        | "templates" | "single" | "p"    | ""    | "keys" | "variables" |
      | 2400    | "i"        | "t"        | "templates" | "single" | "p"    | ""    | "keys" | "x"         |
      | 2413    | "i"        | "t"        | "templates" | "single" | "path" | ""    | ""     | ""          |
      | 2414    | "i"        | "t"        | "templates" | "single" | "path" | ""    | ""     | "variables" |
      | 2415    | "i"        | "t"        | "templates" | "single" | "path" | ""    | ""     | "x"         |
      | 2416    | "i"        | "t"        | "templates" | "single" | "path" | ""    | "keys" | ""          |
      | 2417    | "i"        | "t"        | "templates" | "single" | "path" | ""    | "keys" | "variables" |
      | 2418    | "i"        | "t"        | "templates" | "single" | "path" | ""    | "keys" | "x"         |
      | 2485    | "i"        | "template" | ""          | "multi"  | ""     | ""    | ""     | ""          |
      | 2486    | "i"        | "template" | ""          | "multi"  | ""     | ""    | ""     | "variables" |
      | 2487    | "i"        | "template" | ""          | "multi"  | ""     | ""    | ""     | "x"         |
      | 2488    | "i"        | "template" | ""          | "multi"  | ""     | ""    | "keys" | ""          |
      | 2489    | "i"        | "template" | ""          | "multi"  | ""     | ""    | "keys" | "variables" |
      | 2490    | "i"        | "template" | ""          | "multi"  | ""     | ""    | "keys" | "x"         |
      | 2503    | "i"        | "template" | ""          | "multi"  | "p"    | ""    | ""     | ""          |
      | 2504    | "i"        | "template" | ""          | "multi"  | "p"    | ""    | ""     | "variables" |
      | 2505    | "i"        | "template" | ""          | "multi"  | "p"    | ""    | ""     | "x"         |
      | 2506    | "i"        | "template" | ""          | "multi"  | "p"    | ""    | "keys" | ""          |
      | 2507    | "i"        | "template" | ""          | "multi"  | "p"    | ""    | "keys" | "variables" |
      | 2508    | "i"        | "template" | ""          | "multi"  | "p"    | ""    | "keys" | "x"         |
      | 2521    | "i"        | "template" | ""          | "multi"  | "path" | ""    | ""     | ""          |
      | 2522    | "i"        | "template" | ""          | "multi"  | "path" | ""    | ""     | "variables" |
      | 2523    | "i"        | "template" | ""          | "multi"  | "path" | ""    | ""     | "x"         |
      | 2524    | "i"        | "template" | ""          | "multi"  | "path" | ""    | "keys" | ""          |
      | 2525    | "i"        | "template" | ""          | "multi"  | "path" | ""    | "keys" | "variables" |
      | 2526    | "i"        | "template" | ""          | "multi"  | "path" | ""    | "keys" | "x"         |
      | 2539    | "i"        | "template" | ""          | "single" | ""     | ""    | ""     | ""          |
      | 2540    | "i"        | "template" | ""          | "single" | ""     | ""    | ""     | "variables" |
      | 2541    | "i"        | "template" | ""          | "single" | ""     | ""    | ""     | "x"         |
      | 2542    | "i"        | "template" | ""          | "single" | ""     | ""    | "keys" | ""          |
      | 2543    | "i"        | "template" | ""          | "single" | ""     | ""    | "keys" | "variables" |
      | 2544    | "i"        | "template" | ""          | "single" | ""     | ""    | "keys" | "x"         |
      | 2557    | "i"        | "template" | ""          | "single" | "p"    | ""    | ""     | ""          |
      | 2558    | "i"        | "template" | ""          | "single" | "p"    | ""    | ""     | "variables" |
      | 2559    | "i"        | "template" | ""          | "single" | "p"    | ""    | ""     | "x"         |
      | 2560    | "i"        | "template" | ""          | "single" | "p"    | ""    | "keys" | ""          |
      | 2561    | "i"        | "template" | ""          | "single" | "p"    | ""    | "keys" | "variables" |
      | 2562    | "i"        | "template" | ""          | "single" | "p"    | ""    | "keys" | "x"         |
      | 2575    | "i"        | "template" | ""          | "single" | "path" | ""    | ""     | ""          |
      | 2576    | "i"        | "template" | ""          | "single" | "path" | ""    | ""     | "variables" |
      | 2577    | "i"        | "template" | ""          | "single" | "path" | ""    | ""     | "x"         |
      | 2578    | "i"        | "template" | ""          | "single" | "path" | ""    | "keys" | ""          |
      | 2579    | "i"        | "template" | ""          | "single" | "path" | ""    | "keys" | "variables" |
      | 2580    | "i"        | "template" | ""          | "single" | "path" | ""    | "keys" | "x"         |
      | 2647    | "i"        | "template" | "l"         | "multi"  | ""     | ""    | ""     | ""          |
      | 2648    | "i"        | "template" | "l"         | "multi"  | ""     | ""    | ""     | "variables" |
      | 2649    | "i"        | "template" | "l"         | "multi"  | ""     | ""    | ""     | "x"         |
      | 2650    | "i"        | "template" | "l"         | "multi"  | ""     | ""    | "keys" | ""          |
      | 2651    | "i"        | "template" | "l"         | "multi"  | ""     | ""    | "keys" | "variables" |
      | 2652    | "i"        | "template" | "l"         | "multi"  | ""     | ""    | "keys" | "x"         |
      | 2665    | "i"        | "template" | "l"         | "multi"  | "p"    | ""    | ""     | ""          |
      | 2666    | "i"        | "template" | "l"         | "multi"  | "p"    | ""    | ""     | "variables" |
      | 2667    | "i"        | "template" | "l"         | "multi"  | "p"    | ""    | ""     | "x"         |
      | 2668    | "i"        | "template" | "l"         | "multi"  | "p"    | ""    | "keys" | ""          |
      | 2669    | "i"        | "template" | "l"         | "multi"  | "p"    | ""    | "keys" | "variables" |
      | 2670    | "i"        | "template" | "l"         | "multi"  | "p"    | ""    | "keys" | "x"         |
      | 2683    | "i"        | "template" | "l"         | "multi"  | "path" | ""    | ""     | ""          |
      | 2684    | "i"        | "template" | "l"         | "multi"  | "path" | ""    | ""     | "variables" |
      | 2685    | "i"        | "template" | "l"         | "multi"  | "path" | ""    | ""     | "x"         |
      | 2686    | "i"        | "template" | "l"         | "multi"  | "path" | ""    | "keys" | ""          |
      | 2687    | "i"        | "template" | "l"         | "multi"  | "path" | ""    | "keys" | "variables" |
      | 2688    | "i"        | "template" | "l"         | "multi"  | "path" | ""    | "keys" | "x"         |
      | 2701    | "i"        | "template" | "l"         | "single" | ""     | ""    | ""     | ""          |
      | 2702    | "i"        | "template" | "l"         | "single" | ""     | ""    | ""     | "variables" |
      | 2703    | "i"        | "template" | "l"         | "single" | ""     | ""    | ""     | "x"         |
      | 2704    | "i"        | "template" | "l"         | "single" | ""     | ""    | "keys" | ""          |
      | 2705    | "i"        | "template" | "l"         | "single" | ""     | ""    | "keys" | "variables" |
      | 2706    | "i"        | "template" | "l"         | "single" | ""     | ""    | "keys" | "x"         |
      | 2719    | "i"        | "template" | "l"         | "single" | "p"    | ""    | ""     | ""          |
      | 2720    | "i"        | "template" | "l"         | "single" | "p"    | ""    | ""     | "variables" |
      | 2721    | "i"        | "template" | "l"         | "single" | "p"    | ""    | ""     | "x"         |
      | 2722    | "i"        | "template" | "l"         | "single" | "p"    | ""    | "keys" | ""          |
      | 2723    | "i"        | "template" | "l"         | "single" | "p"    | ""    | "keys" | "variables" |
      | 2724    | "i"        | "template" | "l"         | "single" | "p"    | ""    | "keys" | "x"         |
      | 2737    | "i"        | "template" | "l"         | "single" | "path" | ""    | ""     | ""          |
      | 2738    | "i"        | "template" | "l"         | "single" | "path" | ""    | ""     | "variables" |
      | 2739    | "i"        | "template" | "l"         | "single" | "path" | ""    | ""     | "x"         |
      | 2740    | "i"        | "template" | "l"         | "single" | "path" | ""    | "keys" | ""          |
      | 2741    | "i"        | "template" | "l"         | "single" | "path" | ""    | "keys" | "variables" |
      | 2742    | "i"        | "template" | "l"         | "single" | "path" | ""    | "keys" | "x"         |
      | 2809    | "i"        | "template" | "templates" | "multi"  | ""     | ""    | ""     | ""          |
      | 2810    | "i"        | "template" | "templates" | "multi"  | ""     | ""    | ""     | "variables" |
      | 2811    | "i"        | "template" | "templates" | "multi"  | ""     | ""    | ""     | "x"         |
      | 2812    | "i"        | "template" | "templates" | "multi"  | ""     | ""    | "keys" | ""          |
      | 2813    | "i"        | "template" | "templates" | "multi"  | ""     | ""    | "keys" | "variables" |
      | 2814    | "i"        | "template" | "templates" | "multi"  | ""     | ""    | "keys" | "x"         |
      | 2827    | "i"        | "template" | "templates" | "multi"  | "p"    | ""    | ""     | ""          |
      | 2828    | "i"        | "template" | "templates" | "multi"  | "p"    | ""    | ""     | "variables" |
      | 2829    | "i"        | "template" | "templates" | "multi"  | "p"    | ""    | ""     | "x"         |
      | 2830    | "i"        | "template" | "templates" | "multi"  | "p"    | ""    | "keys" | ""          |
      | 2831    | "i"        | "template" | "templates" | "multi"  | "p"    | ""    | "keys" | "variables" |
      | 2832    | "i"        | "template" | "templates" | "multi"  | "p"    | ""    | "keys" | "x"         |
      | 2845    | "i"        | "template" | "templates" | "multi"  | "path" | ""    | ""     | ""          |
      | 2846    | "i"        | "template" | "templates" | "multi"  | "path" | ""    | ""     | "variables" |
      | 2847    | "i"        | "template" | "templates" | "multi"  | "path" | ""    | ""     | "x"         |
      | 2848    | "i"        | "template" | "templates" | "multi"  | "path" | ""    | "keys" | ""          |
      | 2849    | "i"        | "template" | "templates" | "multi"  | "path" | ""    | "keys" | "variables" |
      | 2850    | "i"        | "template" | "templates" | "multi"  | "path" | ""    | "keys" | "x"         |
      | 2863    | "i"        | "template" | "templates" | "single" | ""     | ""    | ""     | ""          |
      | 2864    | "i"        | "template" | "templates" | "single" | ""     | ""    | ""     | "variables" |
      | 2865    | "i"        | "template" | "templates" | "single" | ""     | ""    | ""     | "x"         |
      | 2866    | "i"        | "template" | "templates" | "single" | ""     | ""    | "keys" | ""          |
      | 2867    | "i"        | "template" | "templates" | "single" | ""     | ""    | "keys" | "variables" |
      | 2868    | "i"        | "template" | "templates" | "single" | ""     | ""    | "keys" | "x"         |
      | 2881    | "i"        | "template" | "templates" | "single" | "p"    | ""    | ""     | ""          |
      | 2882    | "i"        | "template" | "templates" | "single" | "p"    | ""    | ""     | "variables" |
      | 2883    | "i"        | "template" | "templates" | "single" | "p"    | ""    | ""     | "x"         |
      | 2884    | "i"        | "template" | "templates" | "single" | "p"    | ""    | "keys" | ""          |
      | 2885    | "i"        | "template" | "templates" | "single" | "p"    | ""    | "keys" | "variables" |
      | 2886    | "i"        | "template" | "templates" | "single" | "p"    | ""    | "keys" | "x"         |
      | 2899    | "i"        | "template" | "templates" | "single" | "path" | ""    | ""     | ""          |
      | 2900    | "i"        | "template" | "templates" | "single" | "path" | ""    | ""     | "variables" |
      | 2901    | "i"        | "template" | "templates" | "single" | "path" | ""    | ""     | "x"         |
      | 2902    | "i"        | "template" | "templates" | "single" | "path" | ""    | "keys" | ""          |
      | 2903    | "i"        | "template" | "templates" | "single" | "path" | ""    | "keys" | "variables" |
      | 2904    | "i"        | "template" | "templates" | "single" | "path" | ""    | "keys" | "x"         |
      | 3457    | "input"    | "t"        | ""          | "multi"  | ""     | ""    | ""     | ""          |
      | 3458    | "input"    | "t"        | ""          | "multi"  | ""     | ""    | ""     | "variables" |
      | 3459    | "input"    | "t"        | ""          | "multi"  | ""     | ""    | ""     | "x"         |
      | 3460    | "input"    | "t"        | ""          | "multi"  | ""     | ""    | "keys" | ""          |
      | 3461    | "input"    | "t"        | ""          | "multi"  | ""     | ""    | "keys" | "variables" |
      | 3462    | "input"    | "t"        | ""          | "multi"  | ""     | ""    | "keys" | "x"         |
      | 3475    | "input"    | "t"        | ""          | "multi"  | "p"    | ""    | ""     | ""          |
      | 3476    | "input"    | "t"        | ""          | "multi"  | "p"    | ""    | ""     | "variables" |
      | 3477    | "input"    | "t"        | ""          | "multi"  | "p"    | ""    | ""     | "x"         |
      | 3478    | "input"    | "t"        | ""          | "multi"  | "p"    | ""    | "keys" | ""          |
      | 3479    | "input"    | "t"        | ""          | "multi"  | "p"    | ""    | "keys" | "variables" |
      | 3480    | "input"    | "t"        | ""          | "multi"  | "p"    | ""    | "keys" | "x"         |
      | 3493    | "input"    | "t"        | ""          | "multi"  | "path" | ""    | ""     | ""          |
      | 3494    | "input"    | "t"        | ""          | "multi"  | "path" | ""    | ""     | "variables" |
      | 3495    | "input"    | "t"        | ""          | "multi"  | "path" | ""    | ""     | "x"         |
      | 3496    | "input"    | "t"        | ""          | "multi"  | "path" | ""    | "keys" | ""          |
      | 3497    | "input"    | "t"        | ""          | "multi"  | "path" | ""    | "keys" | "variables" |
      | 3498    | "input"    | "t"        | ""          | "multi"  | "path" | ""    | "keys" | "x"         |
      | 3511    | "input"    | "t"        | ""          | "single" | ""     | ""    | ""     | ""          |
      | 3512    | "input"    | "t"        | ""          | "single" | ""     | ""    | ""     | "variables" |
      | 3513    | "input"    | "t"        | ""          | "single" | ""     | ""    | ""     | "x"         |
      | 3514    | "input"    | "t"        | ""          | "single" | ""     | ""    | "keys" | ""          |
      | 3515    | "input"    | "t"        | ""          | "single" | ""     | ""    | "keys" | "variables" |
      | 3516    | "input"    | "t"        | ""          | "single" | ""     | ""    | "keys" | "x"         |
      | 3529    | "input"    | "t"        | ""          | "single" | "p"    | ""    | ""     | ""          |
      | 3530    | "input"    | "t"        | ""          | "single" | "p"    | ""    | ""     | "variables" |
      | 3531    | "input"    | "t"        | ""          | "single" | "p"    | ""    | ""     | "x"         |
      | 3532    | "input"    | "t"        | ""          | "single" | "p"    | ""    | "keys" | ""          |
      | 3533    | "input"    | "t"        | ""          | "single" | "p"    | ""    | "keys" | "variables" |
      | 3534    | "input"    | "t"        | ""          | "single" | "p"    | ""    | "keys" | "x"         |
      | 3547    | "input"    | "t"        | ""          | "single" | "path" | ""    | ""     | ""          |
      | 3548    | "input"    | "t"        | ""          | "single" | "path" | ""    | ""     | "variables" |
      | 3549    | "input"    | "t"        | ""          | "single" | "path" | ""    | ""     | "x"         |
      | 3550    | "input"    | "t"        | ""          | "single" | "path" | ""    | "keys" | ""          |
      | 3551    | "input"    | "t"        | ""          | "single" | "path" | ""    | "keys" | "variables" |
      | 3552    | "input"    | "t"        | ""          | "single" | "path" | ""    | "keys" | "x"         |
      | 3619    | "input"    | "t"        | "l"         | "multi"  | ""     | ""    | ""     | ""          |
      | 3620    | "input"    | "t"        | "l"         | "multi"  | ""     | ""    | ""     | "variables" |
      | 3621    | "input"    | "t"        | "l"         | "multi"  | ""     | ""    | ""     | "x"         |
      | 3622    | "input"    | "t"        | "l"         | "multi"  | ""     | ""    | "keys" | ""          |
      | 3623    | "input"    | "t"        | "l"         | "multi"  | ""     | ""    | "keys" | "variables" |
      | 3624    | "input"    | "t"        | "l"         | "multi"  | ""     | ""    | "keys" | "x"         |
      | 3637    | "input"    | "t"        | "l"         | "multi"  | "p"    | ""    | ""     | ""          |
      | 3638    | "input"    | "t"        | "l"         | "multi"  | "p"    | ""    | ""     | "variables" |
      | 3639    | "input"    | "t"        | "l"         | "multi"  | "p"    | ""    | ""     | "x"         |
      | 3640    | "input"    | "t"        | "l"         | "multi"  | "p"    | ""    | "keys" | ""          |
      | 3641    | "input"    | "t"        | "l"         | "multi"  | "p"    | ""    | "keys" | "variables" |
      | 3642    | "input"    | "t"        | "l"         | "multi"  | "p"    | ""    | "keys" | "x"         |
      | 3655    | "input"    | "t"        | "l"         | "multi"  | "path" | ""    | ""     | ""          |
      | 3656    | "input"    | "t"        | "l"         | "multi"  | "path" | ""    | ""     | "variables" |
      | 3657    | "input"    | "t"        | "l"         | "multi"  | "path" | ""    | ""     | "x"         |
      | 3658    | "input"    | "t"        | "l"         | "multi"  | "path" | ""    | "keys" | ""          |
      | 3659    | "input"    | "t"        | "l"         | "multi"  | "path" | ""    | "keys" | "variables" |
      | 3660    | "input"    | "t"        | "l"         | "multi"  | "path" | ""    | "keys" | "x"         |
      | 3673    | "input"    | "t"        | "l"         | "single" | ""     | ""    | ""     | ""          |
      | 3674    | "input"    | "t"        | "l"         | "single" | ""     | ""    | ""     | "variables" |
      | 3675    | "input"    | "t"        | "l"         | "single" | ""     | ""    | ""     | "x"         |
      | 3676    | "input"    | "t"        | "l"         | "single" | ""     | ""    | "keys" | ""          |
      | 3677    | "input"    | "t"        | "l"         | "single" | ""     | ""    | "keys" | "variables" |
      | 3678    | "input"    | "t"        | "l"         | "single" | ""     | ""    | "keys" | "x"         |
      | 3691    | "input"    | "t"        | "l"         | "single" | "p"    | ""    | ""     | ""          |
      | 3692    | "input"    | "t"        | "l"         | "single" | "p"    | ""    | ""     | "variables" |
      | 3693    | "input"    | "t"        | "l"         | "single" | "p"    | ""    | ""     | "x"         |
      | 3694    | "input"    | "t"        | "l"         | "single" | "p"    | ""    | "keys" | ""          |
      | 3695    | "input"    | "t"        | "l"         | "single" | "p"    | ""    | "keys" | "variables" |
      | 3696    | "input"    | "t"        | "l"         | "single" | "p"    | ""    | "keys" | "x"         |
      | 3709    | "input"    | "t"        | "l"         | "single" | "path" | ""    | ""     | ""          |
      | 3710    | "input"    | "t"        | "l"         | "single" | "path" | ""    | ""     | "variables" |
      | 3711    | "input"    | "t"        | "l"         | "single" | "path" | ""    | ""     | "x"         |
      | 3712    | "input"    | "t"        | "l"         | "single" | "path" | ""    | "keys" | ""          |
      | 3713    | "input"    | "t"        | "l"         | "single" | "path" | ""    | "keys" | "variables" |
      | 3714    | "input"    | "t"        | "l"         | "single" | "path" | ""    | "keys" | "x"         |
      | 3781    | "input"    | "t"        | "templates" | "multi"  | ""     | ""    | ""     | ""          |
      | 3782    | "input"    | "t"        | "templates" | "multi"  | ""     | ""    | ""     | "variables" |
      | 3783    | "input"    | "t"        | "templates" | "multi"  | ""     | ""    | ""     | "x"         |
      | 3784    | "input"    | "t"        | "templates" | "multi"  | ""     | ""    | "keys" | ""          |
      | 3785    | "input"    | "t"        | "templates" | "multi"  | ""     | ""    | "keys" | "variables" |
      | 3786    | "input"    | "t"        | "templates" | "multi"  | ""     | ""    | "keys" | "x"         |
      | 3799    | "input"    | "t"        | "templates" | "multi"  | "p"    | ""    | ""     | ""          |
      | 3800    | "input"    | "t"        | "templates" | "multi"  | "p"    | ""    | ""     | "variables" |
      | 3801    | "input"    | "t"        | "templates" | "multi"  | "p"    | ""    | ""     | "x"         |
      | 3802    | "input"    | "t"        | "templates" | "multi"  | "p"    | ""    | "keys" | ""          |
      | 3803    | "input"    | "t"        | "templates" | "multi"  | "p"    | ""    | "keys" | "variables" |
      | 3804    | "input"    | "t"        | "templates" | "multi"  | "p"    | ""    | "keys" | "x"         |
      | 3817    | "input"    | "t"        | "templates" | "multi"  | "path" | ""    | ""     | ""          |
      | 3818    | "input"    | "t"        | "templates" | "multi"  | "path" | ""    | ""     | "variables" |
      | 3819    | "input"    | "t"        | "templates" | "multi"  | "path" | ""    | ""     | "x"         |
      | 3820    | "input"    | "t"        | "templates" | "multi"  | "path" | ""    | "keys" | ""          |
      | 3821    | "input"    | "t"        | "templates" | "multi"  | "path" | ""    | "keys" | "variables" |
      | 3822    | "input"    | "t"        | "templates" | "multi"  | "path" | ""    | "keys" | "x"         |
      | 3835    | "input"    | "t"        | "templates" | "single" | ""     | ""    | ""     | ""          |
      | 3836    | "input"    | "t"        | "templates" | "single" | ""     | ""    | ""     | "variables" |
      | 3837    | "input"    | "t"        | "templates" | "single" | ""     | ""    | ""     | "x"         |
      | 3838    | "input"    | "t"        | "templates" | "single" | ""     | ""    | "keys" | ""          |
      | 3839    | "input"    | "t"        | "templates" | "single" | ""     | ""    | "keys" | "variables" |
      | 3840    | "input"    | "t"        | "templates" | "single" | ""     | ""    | "keys" | "x"         |
      | 3853    | "input"    | "t"        | "templates" | "single" | "p"    | ""    | ""     | ""          |
      | 3854    | "input"    | "t"        | "templates" | "single" | "p"    | ""    | ""     | "variables" |
      | 3855    | "input"    | "t"        | "templates" | "single" | "p"    | ""    | ""     | "x"         |
      | 3856    | "input"    | "t"        | "templates" | "single" | "p"    | ""    | "keys" | ""          |
      | 3857    | "input"    | "t"        | "templates" | "single" | "p"    | ""    | "keys" | "variables" |
      | 3858    | "input"    | "t"        | "templates" | "single" | "p"    | ""    | "keys" | "x"         |
      | 3871    | "input"    | "t"        | "templates" | "single" | "path" | ""    | ""     | ""          |
      | 3872    | "input"    | "t"        | "templates" | "single" | "path" | ""    | ""     | "variables" |
      | 3873    | "input"    | "t"        | "templates" | "single" | "path" | ""    | ""     | "x"         |
      | 3874    | "input"    | "t"        | "templates" | "single" | "path" | ""    | "keys" | ""          |
      | 3875    | "input"    | "t"        | "templates" | "single" | "path" | ""    | "keys" | "variables" |
      | 3876    | "input"    | "t"        | "templates" | "single" | "path" | ""    | "keys" | "x"         |
      | 3943    | "input"    | "template" | ""          | "multi"  | ""     | ""    | ""     | ""          |
      | 3944    | "input"    | "template" | ""          | "multi"  | ""     | ""    | ""     | "variables" |
      | 3945    | "input"    | "template" | ""          | "multi"  | ""     | ""    | ""     | "x"         |
      | 3946    | "input"    | "template" | ""          | "multi"  | ""     | ""    | "keys" | ""          |
      | 3947    | "input"    | "template" | ""          | "multi"  | ""     | ""    | "keys" | "variables" |
      | 3948    | "input"    | "template" | ""          | "multi"  | ""     | ""    | "keys" | "x"         |
      | 3961    | "input"    | "template" | ""          | "multi"  | "p"    | ""    | ""     | ""          |
      | 3962    | "input"    | "template" | ""          | "multi"  | "p"    | ""    | ""     | "variables" |
      | 3963    | "input"    | "template" | ""          | "multi"  | "p"    | ""    | ""     | "x"         |
      | 3964    | "input"    | "template" | ""          | "multi"  | "p"    | ""    | "keys" | ""          |
      | 3965    | "input"    | "template" | ""          | "multi"  | "p"    | ""    | "keys" | "variables" |
      | 3966    | "input"    | "template" | ""          | "multi"  | "p"    | ""    | "keys" | "x"         |
      | 3979    | "input"    | "template" | ""          | "multi"  | "path" | ""    | ""     | ""          |
      | 3980    | "input"    | "template" | ""          | "multi"  | "path" | ""    | ""     | "variables" |
      | 3981    | "input"    | "template" | ""          | "multi"  | "path" | ""    | ""     | "x"         |
      | 3982    | "input"    | "template" | ""          | "multi"  | "path" | ""    | "keys" | ""          |
      | 3983    | "input"    | "template" | ""          | "multi"  | "path" | ""    | "keys" | "variables" |
      | 3984    | "input"    | "template" | ""          | "multi"  | "path" | ""    | "keys" | "x"         |
      | 3997    | "input"    | "template" | ""          | "single" | ""     | ""    | ""     | ""          |
      | 3998    | "input"    | "template" | ""          | "single" | ""     | ""    | ""     | "variables" |
      | 3999    | "input"    | "template" | ""          | "single" | ""     | ""    | ""     | "x"         |
      | 4000    | "input"    | "template" | ""          | "single" | ""     | ""    | "keys" | ""          |
      | 4001    | "input"    | "template" | ""          | "single" | ""     | ""    | "keys" | "variables" |
      | 4002    | "input"    | "template" | ""          | "single" | ""     | ""    | "keys" | "x"         |
      | 4015    | "input"    | "template" | ""          | "single" | "p"    | ""    | ""     | ""          |
      | 4016    | "input"    | "template" | ""          | "single" | "p"    | ""    | ""     | "variables" |
      | 4017    | "input"    | "template" | ""          | "single" | "p"    | ""    | ""     | "x"         |
      | 4018    | "input"    | "template" | ""          | "single" | "p"    | ""    | "keys" | ""          |
      | 4019    | "input"    | "template" | ""          | "single" | "p"    | ""    | "keys" | "variables" |
      | 4020    | "input"    | "template" | ""          | "single" | "p"    | ""    | "keys" | "x"         |
      | 4033    | "input"    | "template" | ""          | "single" | "path" | ""    | ""     | ""          |
      | 4034    | "input"    | "template" | ""          | "single" | "path" | ""    | ""     | "variables" |
      | 4035    | "input"    | "template" | ""          | "single" | "path" | ""    | ""     | "x"         |
      | 4036    | "input"    | "template" | ""          | "single" | "path" | ""    | "keys" | ""          |
      | 4037    | "input"    | "template" | ""          | "single" | "path" | ""    | "keys" | "variables" |
      | 4038    | "input"    | "template" | ""          | "single" | "path" | ""    | "keys" | "x"         |
      | 4105    | "input"    | "template" | "l"         | "multi"  | ""     | ""    | ""     | ""          |
      | 4106    | "input"    | "template" | "l"         | "multi"  | ""     | ""    | ""     | "variables" |
      | 4107    | "input"    | "template" | "l"         | "multi"  | ""     | ""    | ""     | "x"         |
      | 4108    | "input"    | "template" | "l"         | "multi"  | ""     | ""    | "keys" | ""          |
      | 4109    | "input"    | "template" | "l"         | "multi"  | ""     | ""    | "keys" | "variables" |
      | 4110    | "input"    | "template" | "l"         | "multi"  | ""     | ""    | "keys" | "x"         |
      | 4123    | "input"    | "template" | "l"         | "multi"  | "p"    | ""    | ""     | ""          |
      | 4124    | "input"    | "template" | "l"         | "multi"  | "p"    | ""    | ""     | "variables" |
      | 4125    | "input"    | "template" | "l"         | "multi"  | "p"    | ""    | ""     | "x"         |
      | 4126    | "input"    | "template" | "l"         | "multi"  | "p"    | ""    | "keys" | ""          |
      | 4127    | "input"    | "template" | "l"         | "multi"  | "p"    | ""    | "keys" | "variables" |
      | 4128    | "input"    | "template" | "l"         | "multi"  | "p"    | ""    | "keys" | "x"         |
      | 4141    | "input"    | "template" | "l"         | "multi"  | "path" | ""    | ""     | ""          |
      | 4142    | "input"    | "template" | "l"         | "multi"  | "path" | ""    | ""     | "variables" |
      | 4143    | "input"    | "template" | "l"         | "multi"  | "path" | ""    | ""     | "x"         |
      | 4144    | "input"    | "template" | "l"         | "multi"  | "path" | ""    | "keys" | ""          |
      | 4145    | "input"    | "template" | "l"         | "multi"  | "path" | ""    | "keys" | "variables" |
      | 4146    | "input"    | "template" | "l"         | "multi"  | "path" | ""    | "keys" | "x"         |
      | 4159    | "input"    | "template" | "l"         | "single" | ""     | ""    | ""     | ""          |
      | 4160    | "input"    | "template" | "l"         | "single" | ""     | ""    | ""     | "variables" |
      | 4161    | "input"    | "template" | "l"         | "single" | ""     | ""    | ""     | "x"         |
      | 4162    | "input"    | "template" | "l"         | "single" | ""     | ""    | "keys" | ""          |
      | 4163    | "input"    | "template" | "l"         | "single" | ""     | ""    | "keys" | "variables" |
      | 4164    | "input"    | "template" | "l"         | "single" | ""     | ""    | "keys" | "x"         |
      | 4177    | "input"    | "template" | "l"         | "single" | "p"    | ""    | ""     | ""          |
      | 4178    | "input"    | "template" | "l"         | "single" | "p"    | ""    | ""     | "variables" |
      | 4179    | "input"    | "template" | "l"         | "single" | "p"    | ""    | ""     | "x"         |
      | 4180    | "input"    | "template" | "l"         | "single" | "p"    | ""    | "keys" | ""          |
      | 4181    | "input"    | "template" | "l"         | "single" | "p"    | ""    | "keys" | "variables" |
      | 4182    | "input"    | "template" | "l"         | "single" | "p"    | ""    | "keys" | "x"         |
      | 4195    | "input"    | "template" | "l"         | "single" | "path" | ""    | ""     | ""          |
      | 4196    | "input"    | "template" | "l"         | "single" | "path" | ""    | ""     | "variables" |
      | 4197    | "input"    | "template" | "l"         | "single" | "path" | ""    | ""     | "x"         |
      | 4198    | "input"    | "template" | "l"         | "single" | "path" | ""    | "keys" | ""          |
      | 4199    | "input"    | "template" | "l"         | "single" | "path" | ""    | "keys" | "variables" |
      | 4200    | "input"    | "template" | "l"         | "single" | "path" | ""    | "keys" | "x"         |
      | 4267    | "input"    | "template" | "templates" | "multi"  | ""     | ""    | ""     | ""          |
      | 4268    | "input"    | "template" | "templates" | "multi"  | ""     | ""    | ""     | "variables" |
      | 4269    | "input"    | "template" | "templates" | "multi"  | ""     | ""    | ""     | "x"         |
      | 4270    | "input"    | "template" | "templates" | "multi"  | ""     | ""    | "keys" | ""          |
      | 4271    | "input"    | "template" | "templates" | "multi"  | ""     | ""    | "keys" | "variables" |
      | 4272    | "input"    | "template" | "templates" | "multi"  | ""     | ""    | "keys" | "x"         |
      | 4285    | "input"    | "template" | "templates" | "multi"  | "p"    | ""    | ""     | ""          |
      | 4286    | "input"    | "template" | "templates" | "multi"  | "p"    | ""    | ""     | "variables" |
      | 4287    | "input"    | "template" | "templates" | "multi"  | "p"    | ""    | ""     | "x"         |
      | 4288    | "input"    | "template" | "templates" | "multi"  | "p"    | ""    | "keys" | ""          |
      | 4289    | "input"    | "template" | "templates" | "multi"  | "p"    | ""    | "keys" | "variables" |
      | 4290    | "input"    | "template" | "templates" | "multi"  | "p"    | ""    | "keys" | "x"         |
      | 4303    | "input"    | "template" | "templates" | "multi"  | "path" | ""    | ""     | ""          |
      | 4304    | "input"    | "template" | "templates" | "multi"  | "path" | ""    | ""     | "variables" |
      | 4305    | "input"    | "template" | "templates" | "multi"  | "path" | ""    | ""     | "x"         |
      | 4306    | "input"    | "template" | "templates" | "multi"  | "path" | ""    | "keys" | ""          |
      | 4307    | "input"    | "template" | "templates" | "multi"  | "path" | ""    | "keys" | "variables" |
      | 4308    | "input"    | "template" | "templates" | "multi"  | "path" | ""    | "keys" | "x"         |
      | 4321    | "input"    | "template" | "templates" | "single" | ""     | ""    | ""     | ""          |
      | 4322    | "input"    | "template" | "templates" | "single" | ""     | ""    | ""     | "variables" |
      | 4323    | "input"    | "template" | "templates" | "single" | ""     | ""    | ""     | "x"         |
      | 4324    | "input"    | "template" | "templates" | "single" | ""     | ""    | "keys" | ""          |
      | 4325    | "input"    | "template" | "templates" | "single" | ""     | ""    | "keys" | "variables" |
      | 4326    | "input"    | "template" | "templates" | "single" | ""     | ""    | "keys" | "x"         |
      | 4339    | "input"    | "template" | "templates" | "single" | "p"    | ""    | ""     | ""          |
      | 4340    | "input"    | "template" | "templates" | "single" | "p"    | ""    | ""     | "variables" |
      | 4341    | "input"    | "template" | "templates" | "single" | "p"    | ""    | ""     | "x"         |
      | 4342    | "input"    | "template" | "templates" | "single" | "p"    | ""    | "keys" | ""          |
      | 4343    | "input"    | "template" | "templates" | "single" | "p"    | ""    | "keys" | "variables" |
      | 4344    | "input"    | "template" | "templates" | "single" | "p"    | ""    | "keys" | "x"         |
      | 4357    | "input"    | "template" | "templates" | "single" | "path" | ""    | ""     | ""          |
      | 4358    | "input"    | "template" | "templates" | "single" | "path" | ""    | ""     | "variables" |
      | 4359    | "input"    | "template" | "templates" | "single" | "path" | ""    | ""     | "x"         |
      | 4360    | "input"    | "template" | "templates" | "single" | "path" | ""    | "keys" | ""          |
      | 4361    | "input"    | "template" | "templates" | "single" | "path" | ""    | "keys" | "variables" |
      | 4362    | "input"    | "template" | "templates" | "single" | "path" | ""    | "keys" | "x"         |

  # Test when columns in the file pattern file are blank
  @err0007Blank
  Scenario Outline: err0007Blank
    Given err0007.<pUnique> input file <pInputFile>
    * err0007.<pUnique> list of file patterns where some are blank
    When err0007.<pUnique> the values are passed into Cimerant
    Then err0007.<pUnique> error is thrown

    Examples:
      | pUnique | pInputFile |
      | 3079    | "input"    |

  # Test when columns in the file pattern file are missing
  @err0007Missing
  Scenario Outline: err0007Missing
    Given err0007.<pUnique> input file <pInputFile>
    * err0007.<pUnique> list of file patterns where some are missing
    When err0007.<pUnique> the values are passed into Cimerant
    Then err0007.<pUnique> error is thrown

    Examples:
      | pUnique | pInputFile |
      | 3080    | "input"    |
