package cimerant.antlr.sql.plsql;

import cimerant.antlr.sql.ParseTreeHelper;
import cimerant.antlr.sql.ParseTreeStream;
import cimerant.context.NotNullSet;
import cimerant.context.cimerant.ObjectField;
import cimerant.context.cimerant.ObjectRelationship;
import cimerant.context.sql.SqlContext;
import cimerant.context.sql.SqlRootContext;
import cimerant.context.sql.impl.SqlContextImpl;
import cimerant.context.sql.impl.SqlContextImpl.Field;
import cimerant.context.sql.impl.SqlRootContextImpl;
import cimerant.logger.CimerantLogger;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.ParserRuleContext;
import org.antlr.v4.runtime.tree.ParseTree;
import org.antlr.v4.runtime.tree.TerminalNode;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.Strings;
import sql.plsql.PlSqlParser;
import sql.plsql.PlSqlParserListener;

/**
 * This class provides an empty implementation of {@link PlSqlParserListener}, which can be extended
 * to create a listener which only needs to handle a subset of the available methods.
 */
public class PlSqlParserListenerImpl extends PlSqlParserListenerBase {
  private static CharStream input;
  private static final CimerantLogger logger;

  static {
    logger = CimerantLogger.getLogger(PlSqlParserListenerImpl.class.getName());
  }

  private static void traceChildren(final String methodName, final ParseTree ctx) {
    if (PlSqlParserListenerImpl.logger.isTraceEnabled()) {
      ParseTreeHelper.printChildren(methodName, ctx);
    }
  }

  private boolean newScript = true;
  private SqlRootContext rootContext = null;

  /**
   * {@inheritDoc}
   *
   * <p>The default implementation does nothing.
   */
  @Override
  public void enterCreate_table(final PlSqlParser.Create_tableContext ctx) {
    final var methodName = "enterCreate_table";
    PlSqlParserListenerImpl.traceChildren(methodName, ctx);

    this.newScript = true;
  }

  /**
   * {@inheritDoc}
   *
   * <p>The default implementation does nothing.
   */
  @Override
  public void exitColumn_definition(final PlSqlParser.Column_definitionContext ctx) {
    final var methodName = "exitColumn_definition";
    PlSqlParserListenerImpl.traceChildren(methodName, ctx);

    if (ctx == null || ctx.children == null || ctx.children.isEmpty()) {
      return;
    }

    final var currentFieldList = this.getCurrentFieldList(ctx);
    if (currentFieldList == null || currentFieldList.isEmpty()) {
      return;
    }

    ParseTreeStream.parseTreeStream(ctx)
        .streamTextByClass(PlSqlParserListenerImpl.input, PlSqlParser.Identity_clauseContext.class)
        .forEach(
            intervalText -> {
              if (StringUtils.isNoneBlank(intervalText)) {
                if (StringUtils.upperCase(intervalText, Locale.getDefault())
                        .contains("GENERATED ALWAYS AS IDENTITY")
                    || StringUtils.upperCase(intervalText, Locale.getDefault())
                        .contains("GENERATED BY DEFAULT AS IDENTITY")
                    || StringUtils.upperCase(intervalText, Locale.getDefault())
                        .contains("GENERATED BY DEFAULT ON NULL AS IDENTITY")) {
                  for (final var currentField : currentFieldList) {
                    currentField.put(Field.IDENTITY, NotNullSet.getInstance(Boolean.TRUE));
                  }
                } else {
                  final var intervalTextSplit = intervalText.split(" ", 2);
                  if (1 < intervalTextSplit.length) {
                    final var value = intervalTextSplit[1];
                    if (StringUtils.isNoneBlank(value)) {
                      for (final var currentField : currentFieldList) {
                        currentField.put(
                            StringUtils.lowerCase(intervalTextSplit[0], Locale.getDefault()),
                            NotNullSet.getInstance(value));
                      }
                    }
                  }
                }
              }
            });
    ParseTreeStream.parseTreeStream(ctx)
        .streamChildrenByClass(PlSqlParser.Inline_constraintContext.class)
        .streamChildrenByClass(PlSqlParser.Constraint_stateContext.class)
        .streamTerminalNodeString()
        .map(StringUtils::lowerCase)
        .forEach(
            terminalNodeText -> {
              if (!Strings.CI.equals("INITIALLY", terminalNodeText)
                  && !Strings.CI.equals("IMMEDIATE", terminalNodeText)) {
                for (final var currentField : currentFieldList) {
                  // ENABLE
                  currentField.put(terminalNodeText, NotNullSet.getInstance(Boolean.TRUE));
                }
              }
            });
    ParseTreeStream.parseTreeStream(ctx)
        .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
        .streamTerminalNodeString()
        .forEach(
            terminalNodeText -> {
              for (final var currentField : currentFieldList) {
                if (!currentField.containsKey(Field.FIELD_TYPE)) {
                  currentField.put(Field.FIELD_TYPE, NotNullSet.getInstance(terminalNodeText));
                } else if (!currentField.get(Field.FIELD_TYPE).get(0).equals(terminalNodeText)) {
                  currentField.put(
                      StringUtils.lowerCase(terminalNodeText, Locale.getDefault()),
                      NotNullSet.getInstance(Boolean.TRUE));
                }
              }
            });
    final var nativeDatatypeElementText =
        ParseTreeStream.parseTreeStream(ctx)
            .streamChildrenByClass(PlSqlParser.DatatypeContext.class)
            .streamChildrenByClass(PlSqlParser.Native_datatype_elementContext.class)
            .streamTerminalNodeString()
            .collect(Collectors.joining(" "));
    if (StringUtils.isNotBlank(nativeDatatypeElementText)) {
      for (final var currentField : currentFieldList) {
        if (!currentField.containsKey(Field.FIELD_TYPE)) {
          currentField.put(Field.FIELD_TYPE, NotNullSet.getInstance(nativeDatatypeElementText));
        } else if (!currentField.get(Field.FIELD_TYPE).get(0).equals(nativeDatatypeElementText)) {
          currentField.put(
              StringUtils.lowerCase(nativeDatatypeElementText, Locale.getDefault()),
              NotNullSet.getInstance(Boolean.TRUE));
        }
      }
    }
    ParseTreeStream.parseTreeStream(ctx)
        .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
        .streamChildrenByClass(PlSqlParser.Non_reserved_keywords_pre12cContext.class)
        .streamTerminalNodeString()
        .forEach(
            terminalNodeText -> {
              for (final var currentField : currentFieldList) {
                if (!currentField.containsKey(Field.FIELD_TYPE)) {
                  currentField.put(Field.FIELD_TYPE, NotNullSet.getInstance(terminalNodeText));
                } else if (!currentField.get(Field.FIELD_TYPE).get(0).equals(terminalNodeText)) {
                  currentField.put(
                      StringUtils.lowerCase(terminalNodeText, Locale.getDefault()),
                      NotNullSet.getInstance(Boolean.TRUE));
                }
              }
            });
    ParseTreeStream.parseTreeStream(ctx)
        .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
        .streamChildrenByClass(PlSqlParser.Non_reserved_keywords_in_12cContext.class)
        .streamTerminalNodeString()
        .forEach(
            terminalNodeText -> {
              for (final var currentField : currentFieldList) {
                if (!currentField.containsKey(Field.FIELD_TYPE)) {
                  currentField.put(Field.FIELD_TYPE, NotNullSet.getInstance(terminalNodeText));
                } else if (!currentField.get(Field.FIELD_TYPE).get(0).equals(terminalNodeText)) {
                  currentField.put(
                      StringUtils.lowerCase(terminalNodeText, Locale.getDefault()),
                      NotNullSet.getInstance(Boolean.TRUE));
                }
              }
            });
    ParseTreeStream.parseTreeStream(ctx)
        .streamChildrenByClass(PlSqlParser.DatatypeContext.class)
        .streamChildrenByClass(PlSqlParser.Precision_partContext.class)
        .streamTerminalNodeString()
        .map(StringUtils::lowerCase)
        .forEach(
            terminalNodeText -> {
              // [CHAR | VARCHAR2][(maximum_size [CHAR | BYTE])]
              for (final var currentField : currentFieldList) {
                currentField.put(terminalNodeText, NotNullSet.getInstance(Boolean.TRUE));
              }
            });
    ParseTreeStream.parseTreeStream(ctx)
        .streamChildrenByClass(PlSqlParser.DatatypeContext.class)
        .streamChildrenByClass(PlSqlParser.Precision_partContext.class)
        .filter(
            precisionPartContext ->
                precisionPartContext instanceof PlSqlParser.NumericContext
                    || precisionPartContext instanceof PlSqlParser.Numeric_negativeContext)
        .filter(Objects::nonNull)
        .map(parserRuleContext -> ParseTreeHelper.trimToken(parserRuleContext.getText()))
        .forEach(
            parserRuleText -> {
              for (final var currentField : currentFieldList) {
                if (this.newScript || !currentField.containsKey(Field.PRECISION)) {
                  this.newScript = false;
                  if (parserRuleText.contains(".")) {
                    final var terminalNodeSplit = parserRuleText.split("\\.", 0);
                    currentField.put(Field.PRECISION, NotNullSet.getInstance(terminalNodeSplit[0]));
                    currentField.put(Field.SCALE, NotNullSet.getInstance(terminalNodeSplit[1]));
                  } else {
                    currentField.put(Field.PRECISION, NotNullSet.getInstance(parserRuleText));
                  }
                } else if (!currentField.containsKey(Field.SCALE)) {
                  currentField.put(Field.SCALE, NotNullSet.getInstance(parserRuleText));
                }
              }
            });
    for (final var currentField : currentFieldList) {
      if (currentField.containsKey(Field.PRECISION)
          && !currentField.containsKey(Field.SCALE)
          && Stream.of(
                  "BINARY",
                  "BIT",
                  "BLOB",
                  "CHAR",
                  "CHARACTER",
                  "DATE",
                  "DATETIME",
                  "NCHAR",
                  "NVARCHAR",
                  "TIME",
                  "TIMESTAMP",
                  "VARBINARY",
                  "VARCHAR",
                  "VARCHAR2",
                  "YEAR")
              .anyMatch(currentField.get(Field.FIELD_TYPE).toString()::equalsIgnoreCase)) {
        currentField.put(Field.MAX_SIZE, currentField.get(Field.PRECISION));
        currentField.remove(Field.PRECISION);
      }
    }
    ParseTreeStream.parseTreeStream(ctx)
        .streamTerminalNodeString()
        .map(StringUtils::upperCase)
        .forEach(
            terminalNodeText -> {
              switch (terminalNodeText) {
                case "DEFAULT":
                  {
                    ParseTreeStream.parseTreeStream(ctx)
                        .streamTextByClass(
                            PlSqlParserListenerImpl.input, PlSqlParser.ExpressionContext.class)
                        .map(ParseTreeHelper::trimParentheses)
                        .filter(StringUtils::isNoneBlank)
                        .forEach(
                            intervalText -> {
                              for (final var currentField : currentFieldList) {
                                currentField.put(
                                    StringUtils.lowerCase(terminalNodeText, Locale.getDefault()),
                                    NotNullSet.getInstance(intervalText));
                              }
                            });
                    break;
                  }
                case "ENCRYPT":
                  {
                    ParseTreeStream.parseTreeStream(ctx)
                        .streamTextByClass(
                            PlSqlParserListenerImpl.input, PlSqlParser.Encryption_specContext.class)
                        .filter(StringUtils::isNoneBlank)
                        .forEach(
                            intervalText -> {
                              for (final var currentField : currentFieldList) {
                                currentField.put(
                                    StringUtils.lowerCase(terminalNodeText, Locale.getDefault()),
                                    NotNullSet.getInstance(intervalText));
                              }
                            });
                    break;
                  }
                case "INVISIBLE":
                  for (final var currentField : currentFieldList) {
                    currentField.put(Field.VISIBLE, NotNullSet.getInstance(Boolean.FALSE));
                  }
                  break;
                case "VISIBLE":
                  for (final var currentField : currentFieldList) {
                    currentField.put(Field.VISIBLE, NotNullSet.getInstance(Boolean.TRUE));
                  }
                  break;
                default:
                  for (final var currentField : currentFieldList) {
                    currentField.put(
                        StringUtils.lowerCase(terminalNodeText, Locale.getDefault()),
                        NotNullSet.getInstance(Boolean.TRUE));
                  }
                  break;
              }
            });
    ParseTreeStream.parseTreeStream(ctx)
        .streamChildrenByClass(PlSqlParser.DatatypeContext.class)
        .streamChildrenByClass(PlSqlParser.Char_set_nameContext.class)
        .streamChildrenByClass(PlSqlParser.Id_expressionContext.class)
        .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
        .streamTerminalNodeString()
        .forEach(
            terminalNodeText -> {
              for (final var currentField : currentFieldList) {
                currentField.put(Field.CHARSET, NotNullSet.getInstance(terminalNodeText));
              }
            });
    ParseTreeStream.parseTreeStream(ctx)
        .streamChildrenByClass(PlSqlParser.Column_collation_nameContext.class)
        .streamChildrenByClass(PlSqlParser.Id_expressionContext.class)
        .streamTerminalNodeString()
        .forEach(
            terminalNodeText -> {
              for (final var currentField : currentFieldList) {
                currentField.put(Field.COLLATION_NAME, NotNullSet.getInstance(terminalNodeText));
              }
            });
    ParseTreeStream.parseTreeStream(ctx)
        .streamChildrenByClass(PlSqlParser.Column_collation_nameContext.class)
        .streamChildrenByClass(PlSqlParser.Id_expressionContext.class)
        .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
        .streamTerminalNodeString()
        .forEach(
            terminalNodeText -> {
              for (final var currentField : currentFieldList) {
                currentField.put(Field.COLLATION_NAME, NotNullSet.getInstance(terminalNodeText));
              }
            });
    var primaryKeyText = " ";
    primaryKeyText +=
        ParseTreeStream.parseTreeStream(ctx)
            .streamChildrenByClass(PlSqlParser.Inline_constraintContext.class)
            .streamTerminalNodeString()
            .map(StringUtils::upperCase)
            .collect(Collectors.joining(" "));
    primaryKeyText += " ";
    primaryKeyText +=
        ParseTreeStream.parseTreeStream(ctx)
            .streamChildrenByClass(PlSqlParser.Inline_constraintContext.class)
            .streamChildrenByClass(PlSqlParser.Check_constraintContext.class)
            .streamChildrenByClass(PlSqlParser.ConditionContext.class)
            .streamChildrenByClass(PlSqlParser.ExpressionContext.class)
            .streamChildrenByClass(PlSqlParser.Logical_expressionContext.class)
            .streamChildrenByClass(PlSqlParser.Unary_logical_expressionContext.class)
            .streamChildrenByClass(PlSqlParser.Unary_logical_operationContext.class)
            .listAllTerminalNodeText()
            .stream()
            .map(StringUtils::upperCase)
            .collect(Collectors.joining(" "));
    primaryKeyText += " ";
    for (final var currentField : currentFieldList) {
      if (primaryKeyText.contains(" PRIMARY KEY ")) {
        currentField.put(Field.PRIMARY, NotNullSet.getInstance(Boolean.TRUE));
      }
      if (primaryKeyText.contains(" NOT NULL ")) {
        currentField.put(Field.NULLABLE, NotNullSet.getInstance(Boolean.FALSE));
      } else if (primaryKeyText.contains(" NULL ")) {
        currentField.put(Field.NULLABLE, NotNullSet.getInstance(Boolean.TRUE));
      }
      if (primaryKeyText.contains(" UNIQUE ")) {
        currentField.put(Field.UNIQUE, NotNullSet.getInstance(Boolean.TRUE));
      }
    }
    final var timeZoneText =
        " "
            + ParseTreeStream.parseTreeStream(ctx)
                .streamChildrenByClass(PlSqlParser.DatatypeContext.class)
                .streamTerminalNodeString()
                .map(StringUtils::upperCase)
                .collect(Collectors.joining(" "))
            + " ";
    if (timeZoneText.contains(" WITH TIME ZONE ")) {
      for (final var currentField : currentFieldList) {
        currentField.put(Field.TIMEZONE, NotNullSet.getInstance(Boolean.TRUE));
      }
    } else if (timeZoneText.contains(" WITH LOCAL TIME ZONE ")) {
      for (final var currentField : currentFieldList) {
        currentField.put(Field.TIMEZONE, NotNullSet.getInstance(Boolean.FALSE));
      }
    }

    final var currentRelationship = this.getCurrentRelationship(ctx);
    if (currentRelationship != null) {
      ParseTreeStream.parseTreeStream(ctx)
          .streamChildrenByClass(PlSqlParser.Column_nameContext.class)
          .streamChildrenByClass(PlSqlParser.IdentifierContext.class)
          .streamChildrenByClass(PlSqlParser.Id_expressionContext.class)
          .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
          .map(regularIdContext -> ParseTreeHelper.trimToken(regularIdContext.getText()))
          .filter(StringUtils::isNoneBlank)
          .forEach(
              regularIdText -> {
                final Set<String> inheritsList;
                if (currentRelationship.get("column") instanceof Set) {
                  inheritsList = (Set<String>) currentRelationship.get("column");
                } else {
                  inheritsList = new LinkedHashSet<>();
                }
                inheritsList.add(regularIdText);

                currentRelationship.put("column", NotNullSet.getInstance(inheritsList));
              });
      ParseTreeStream.parseTreeStream(ctx)
          .streamChildrenByClass(PlSqlParser.Inline_constraintContext.class)
          .streamChildrenByClass(PlSqlParser.References_clauseContext.class)
          .streamChildrenByClass(PlSqlParser.Tableview_nameContext.class)
          .map(tableviewNameContext -> ParseTreeHelper.trimToken(tableviewNameContext.getText()))
          .filter(StringUtils::isNoneBlank)
          .forEach(
              tableviewNameText ->
                  currentRelationship.put(
                      "foreignTable",
                      NotNullSet.getInstance(ParseTreeHelper.trimToken(tableviewNameText))));
      ParseTreeStream.parseTreeStream(ctx)
          .streamChildrenByClass(PlSqlParser.Inline_constraintContext.class)
          .streamChildrenByClass(PlSqlParser.References_clauseContext.class)
          .streamChildrenByClass(PlSqlParser.Paren_column_listContext.class)
          .streamChildrenByClass(PlSqlParser.Column_listContext.class)
          .streamChildrenByClass(PlSqlParser.Column_nameContext.class)
          .streamChildrenByClass(PlSqlParser.IdentifierContext.class)
          .streamChildrenByClass(PlSqlParser.Id_expressionContext.class)
          .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
          .map(regularIdContext -> ParseTreeHelper.trimToken(regularIdContext.getText()))
          .filter(StringUtils::isNoneBlank)
          .forEach(
              regularIdText -> {
                final Set<String> inheritsList;
                if (currentRelationship.get("foreignColumn") instanceof Set) {
                  inheritsList = (Set<String>) currentRelationship.get("foreignColumn");
                } else {
                  inheritsList = new LinkedHashSet<>();
                }
                inheritsList.add(regularIdText);

                currentRelationship.put("foreignColumn", NotNullSet.getInstance(inheritsList));
              });
    }
  }

  /**
   * {@inheritDoc}
   *
   * <p>The default implementation does nothing.
   */
  @Override
  public void exitCreate_table(final PlSqlParser.Create_tableContext ctx) {
    final var methodName = "exitCreate_table";
    PlSqlParserListenerImpl.traceChildren(methodName, ctx);

    if (ctx == null || ctx.children == null || ctx.children.isEmpty()) {
      return;
    }

    final var currentTable = this.getCurrentTable(ctx);
    if (currentTable == null) {
      return;
    }

    final var terminalNodeList =
        ParseTreeStream.parseTreeStream(ctx)
            .streamTerminalNodeString()
            .map(StringUtils::upperCase)
            .collect(Collectors.toSet());
    if (terminalNodeList.contains("BLOCKCHAIN")) {
      currentTable
          .getAttributes()
          .put(SqlContextImpl.BLOCKCHAIN, NotNullSet.getInstance(Boolean.TRUE));
    }
    if (terminalNodeList.contains("QUEUE")) {
      currentTable.getAttributes().put(SqlContextImpl.QUEUE, NotNullSet.getInstance(Boolean.TRUE));
    }

    final Set<String> fieldsToRemove = new TreeSet<>();
    for (final var field : currentTable.getFields().entrySet()) {
      if (!field.getValue().containsKey(Field.FIELD_TYPE)
          || Strings.CI.equals("CONSTRAINT", field.getKey())) {
        fieldsToRemove.add(field.getKey());
      }
    }
    for (final var field : fieldsToRemove) {
      currentTable.getFields().remove(field);
    }
    final Set<String> relationshipsToRemove = new TreeSet<>();
    for (final var relationship : currentTable.getRelationships().entrySet()) {
      if (!relationship.getValue().containsKey("column")
          || !relationship.getValue().containsKey("foreignTable")) {
        relationshipsToRemove.add(relationship.getKey());
      }
    }
    for (final var relationship : relationshipsToRemove) {
      currentTable.getRelationships().remove(relationship);
    }

    if (!currentTable.getFields().isEmpty() || !currentTable.getAttributes().isEmpty()) {
      this.getRootContext().addObject(currentTable);
    }
  }

  /**
   * {@inheritDoc}
   *
   * <p>The default implementation does nothing.
   */
  @Override
  public void exitOut_of_line_constraint(final PlSqlParser.Out_of_line_constraintContext ctx) {
    final var methodName = "exitOut_of_line_constraint";
    PlSqlParserListenerImpl.traceChildren(methodName, ctx);

    if (ctx == null || ctx.children == null || ctx.children.isEmpty()) {
      return;
    }

    final var currentTable = this.getCurrentTable(ctx);
    if (currentTable == null) {
      return;
    }

    final var fieldType =
        ParseTreeStream.parseTreeStream(ctx)
            .streamTerminalNodeString()
            .map(StringUtils::upperCase)
            .collect(Collectors.toSet());
    fieldType.addAll(
        ParseTreeStream.parseTreeStream(ctx)
            .streamChildrenByClass(PlSqlParser.Constraint_stateContext.class)
            .streamTerminalNodeString()
            .map(StringUtils::upperCase)
            .collect(Collectors.toSet()));
    ParseTreeStream.parseTreeStream(ctx)
        .streamChildrenByClass(PlSqlParser.Column_nameContext.class)
        .streamChildrenByClass(PlSqlParser.IdentifierContext.class)
        .streamChildrenByClass(PlSqlParser.Id_expressionContext.class)
        .filter(TerminalNode.class::isInstance)
        .forEach(
            terminalNode -> {
              final var field = ParseTreeHelper.getField(currentTable, terminalNode);
              if (field != null) {
                if (fieldType.contains("PRIMARY")) {
                  if (!field.containsKey(Field.PRIMARY)) {
                    field.put(Field.PRIMARY, NotNullSet.getInstance(Boolean.TRUE));
                  }
                } else if (fieldType.contains("UNIQUE") && !field.containsKey(Field.UNIQUE)) {
                  field.put(Field.UNIQUE, NotNullSet.getInstance(Boolean.TRUE));
                } else if (fieldType.contains("NOT")
                    && fieldType.contains("NULL")
                    && !field.containsKey(Field.NULLABLE)) {
                  field.put(Field.NULLABLE, NotNullSet.getInstance(Boolean.FALSE));
                }
                if (fieldType.contains("DEFERRABLE") && !field.containsKey(Field.DEFERRABLE)) {
                  field.put(Field.DEFERRABLE, NotNullSet.getInstance(Boolean.TRUE));
                }
              }
            });
    ParseTreeStream.parseTreeStream(ctx)
        .streamChildrenByClass(PlSqlParser.Column_nameContext.class)
        .streamChildrenByClass(PlSqlParser.IdentifierContext.class)
        .streamChildrenByClass(PlSqlParser.Id_expressionContext.class)
        .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
        .filter(TerminalNode.class::isInstance)
        .forEach(
            terminalNode -> {
              final var field = ParseTreeHelper.getField(currentTable, terminalNode);
              if (field != null) {
                if (fieldType.contains("PRIMARY")) {
                  if (!field.containsKey(Field.PRIMARY)) {
                    field.put(Field.PRIMARY, NotNullSet.getInstance(Boolean.TRUE));
                  }
                } else if (fieldType.contains("UNIQUE") && !field.containsKey(Field.UNIQUE)) {
                  field.put(Field.UNIQUE, NotNullSet.getInstance(Boolean.TRUE));
                } else if (fieldType.contains("NOT")
                    && fieldType.contains("NULL")
                    && !field.containsKey(Field.NULLABLE)) {
                  field.put(Field.NULLABLE, NotNullSet.getInstance(Boolean.FALSE));
                }
                if (fieldType.contains("DEFERRABLE") && !field.containsKey(Field.DEFERRABLE)) {
                  field.put(Field.DEFERRABLE, NotNullSet.getInstance(Boolean.TRUE));
                }
              }
            });
    ParseTreeStream.parseTreeStream(ctx)
        .streamChildrenByClass(PlSqlParser.Column_nameContext.class)
        .streamChildrenByClass(PlSqlParser.IdentifierContext.class)
        .streamChildrenByClass(PlSqlParser.Id_expressionContext.class)
        .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
        .streamChildrenByClass(PlSqlParser.Non_reserved_keywords_pre12cContext.class)
        .filter(TerminalNode.class::isInstance)
        .forEach(
            terminalNode -> {
              final var field = ParseTreeHelper.getField(currentTable, terminalNode);
              if (field != null) {
                if (fieldType.contains("PRIMARY")) {
                  if (!field.containsKey(Field.PRIMARY)) {
                    field.put(Field.PRIMARY, NotNullSet.getInstance(Boolean.TRUE));
                  }
                } else if (fieldType.contains("UNIQUE") && !field.containsKey(Field.UNIQUE)) {
                  field.put(Field.UNIQUE, NotNullSet.getInstance(Boolean.TRUE));
                } else if (fieldType.contains("NOT")
                    && fieldType.contains("NULL")
                    && !field.containsKey(Field.NULLABLE)) {
                  field.put(Field.NULLABLE, NotNullSet.getInstance(Boolean.FALSE));
                }
                if (fieldType.contains("DEFERRABLE") && !field.containsKey(Field.DEFERRABLE)) {
                  field.put(Field.DEFERRABLE, NotNullSet.getInstance(Boolean.TRUE));
                }
              }
            });

    final var foreignText =
        new StringBuilder()
            .append(
                ParseTreeStream.parseTreeStream(ctx)
                    .streamChildrenByClass(PlSqlParser.Foreign_key_clauseContext.class)
                    .streamTerminalNodeString()
                    .map(StringUtils::upperCase)
                    .collect(Collectors.joining(" ")));
    if (foreignText.toString().contains("FOREIGN KEY")) {
      final var currentRelationship = this.getCurrentRelationship(ctx);
      if (currentRelationship != null) {
        ParseTreeStream.parseTreeStream(ctx)
            .streamChildrenByClass(PlSqlParser.Foreign_key_clauseContext.class)
            .streamChildrenByClass(PlSqlParser.References_clauseContext.class)
            .streamChildrenByClass(PlSqlParser.Tableview_nameContext.class)
            .streamChildrenByClass(PlSqlParser.IdentifierContext.class)
            .streamChildrenByClass(PlSqlParser.Id_expressionContext.class)
            .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
            .streamTerminalNodeString()
            .forEach(
                terminalNodeText ->
                    currentRelationship.put(
                        "foreignTable", NotNullSet.getInstance(terminalNodeText)));
        ParseTreeStream.parseTreeStream(ctx)
            .streamChildrenByClass(PlSqlParser.Foreign_key_clauseContext.class)
            .streamChildrenByClass(PlSqlParser.References_clauseContext.class)
            .streamChildrenByClass(PlSqlParser.Paren_column_listContext.class)
            .streamChildrenByClass(PlSqlParser.Column_listContext.class)
            .streamChildrenByClass(PlSqlParser.Column_nameContext.class)
            .streamChildrenByClass(PlSqlParser.IdentifierContext.class)
            .streamChildrenByClass(PlSqlParser.Id_expressionContext.class)
            .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
            .streamTerminalNodeString()
            .forEach(
                terminalNodeText -> {
                  final Set<String> inheritsList;
                  if (currentRelationship.get("foreignColumn") instanceof Set) {
                    inheritsList = (Set<String>) currentRelationship.get("foreignColumn");
                  } else {
                    inheritsList = new LinkedHashSet<>();
                  }
                  inheritsList.add(terminalNodeText);

                  currentRelationship.put("foreignColumn", NotNullSet.getInstance(inheritsList));
                });
        ParseTreeStream.parseTreeStream(ctx)
            .streamChildrenByClass(PlSqlParser.Foreign_key_clauseContext.class)
            .streamChildrenByClass(PlSqlParser.Paren_column_listContext.class)
            .streamChildrenByClass(PlSqlParser.Column_listContext.class)
            .streamChildrenByClass(PlSqlParser.Column_nameContext.class)
            .streamChildrenByClass(PlSqlParser.IdentifierContext.class)
            .streamChildrenByClass(PlSqlParser.Id_expressionContext.class)
            .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
            .map(regularIdContext -> ParseTreeHelper.trimToken(regularIdContext.getText()))
            .filter(StringUtils::isNoneBlank)
            .forEach(
                regularIdText -> {
                  final Set<String> inheritsList;
                  if (currentRelationship.get("column") instanceof Set) {
                    inheritsList = (Set<String>) currentRelationship.get("column");
                  } else {
                    inheritsList = new LinkedHashSet<>();
                  }
                  inheritsList.add(regularIdText);

                  currentRelationship.put("column", NotNullSet.getInstance(inheritsList));
                });
      }
    }
  }

  private List<ObjectField> getCurrentFieldList(final ParserRuleContext ctx) {
    final var methodName = "getCurrentFieldList";
    PlSqlParserListenerImpl.traceChildren(methodName, ctx);

    if (ctx == null || ctx.children == null || ctx.children.isEmpty()) {
      return null;
    }

    final var currentTable = this.getCurrentTable(ctx);
    if (currentTable == null) {
      return null;
    }

    final var parentContext =
        ParseTreeHelper.getParentContext(ctx, PlSqlParser.Column_definitionContext.class);

    final var terminalNode =
        ParseTreeStream.parseTreeStream(parentContext)
            .streamChildrenByClass(PlSqlParser.Column_nameContext.class)
            .streamChildrenByClass(PlSqlParser.Id_expressionContext.class)
            .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
            .filter(TerminalNode.class::isInstance)
            .collect(Collectors.toSet());

    final var idExpressionChildrenList =
        ParseTreeStream.parseTreeStream(parentContext)
            .streamChildrenByClass(PlSqlParser.Column_nameContext.class)
            .streamChildrenByClass(PlSqlParser.IdentifierContext.class)
            .listChildrenByClass(PlSqlParser.Id_expressionContext.class);

    terminalNode.addAll(
        ParseTreeStream.parseTreeStream(idExpressionChildrenList)
            .filter(TerminalNode.class::isInstance)
            .collect(Collectors.toSet()));

    final var regularIdChildrenList =
        ParseTreeStream.parseTreeStream(idExpressionChildrenList)
            .listChildrenByClass(PlSqlParser.Regular_idContext.class);
    if (terminalNode.isEmpty()) {
      terminalNode.addAll(
          ParseTreeStream.parseTreeStream(regularIdChildrenList)
              .filter(TerminalNode.class::isInstance)
              .collect(Collectors.toSet()));
    }
    terminalNode.addAll(
        ParseTreeStream.parseTreeStream(regularIdChildrenList)
            .streamChildrenByClass(PlSqlParser.Non_reserved_keywords_in_12cContext.class)
            .filter(TerminalNode.class::isInstance)
            .collect(Collectors.toSet()));
    terminalNode.addAll(
        ParseTreeStream.parseTreeStream(regularIdChildrenList)
            .streamChildrenByClass(PlSqlParser.Non_reserved_keywords_pre12cContext.class)
            .filter(TerminalNode.class::isInstance)
            .collect(Collectors.toSet()));

    return terminalNode.stream()
        .map(child -> ParseTreeHelper.getField(currentTable, child))
        .collect(Collectors.toList());
  }

  private ObjectRelationship getCurrentRelationship(final ParserRuleContext ctx) {
    final var methodName = "getCurrentRelationshipList";
    PlSqlParserListenerImpl.traceChildren(methodName, ctx);

    if (ctx == null || ctx.children == null || ctx.children.isEmpty()) {
      return null;
    }

    final var currentTable = this.getCurrentTable(ctx);
    if (currentTable == null) {
      return null;
    }

    final var parentContext =
        ParseTreeHelper.getParentContext(ctx, PlSqlParser.Column_definitionContext.class);
    final List<ParseTree> terminalNode = new ArrayList<>();
    terminalNode.addAll(
        ParseTreeStream.parseTreeStream(parentContext)
            .streamChildrenByClass(PlSqlParser.Inline_constraintContext.class)
            .streamChildrenByClass(PlSqlParser.References_clauseContext.class)
            .filter(TerminalNode.class::isInstance)
            .map(
                foreignTerminalNode -> {
                  final List<ParseTree> returnValue = new ArrayList<>();
                  if (Strings.CI.equalsAny("REFERENCES", foreignTerminalNode.getText())) {
                    returnValue.addAll(
                        ParseTreeStream.parseTreeStream(parentContext)
                            .streamChildrenByClass(PlSqlParser.Inline_constraintContext.class)
                            .streamChildrenByClass(PlSqlParser.Constraint_nameContext.class)
                            .streamChildrenByClass(PlSqlParser.IdentifierContext.class)
                            .streamChildrenByClass(PlSqlParser.Id_expressionContext.class)
                            .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
                            .filter(TerminalNode.class::isInstance)
                            .toList());
                    if (returnValue.isEmpty()) {
                      returnValue.addAll(
                          ParseTreeStream.parseTreeStream(parentContext)
                              .streamChildrenByClass(PlSqlParser.Column_nameContext.class)
                              .streamChildrenByClass(PlSqlParser.IdentifierContext.class)
                              .streamChildrenByClass(PlSqlParser.Id_expressionContext.class)
                              .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
                              .listAllTerminalNode()
                              .stream()
                              .toList());
                    }
                  }
                  return returnValue;
                })
            .flatMap(List::stream)
            .collect(Collectors.toCollection(ArrayList::new)));
    terminalNode.addAll(
        ParseTreeStream.parseTreeStream(ctx)
            .streamChildrenByClass(PlSqlParser.Foreign_key_clauseContext.class)
            .streamChildrenByClass(PlSqlParser.References_clauseContext.class)
            .filter(TerminalNode.class::isInstance)
            .map(
                foreignTerminalNode -> {
                  final List<ParseTree> returnValue = new ArrayList<>();
                  if (Strings.CI.equalsAny("REFERENCES", foreignTerminalNode.getText())) {
                    returnValue.addAll(
                        ParseTreeStream.parseTreeStream(ctx)
                            .streamChildrenByClass(PlSqlParser.Constraint_nameContext.class)
                            .streamChildrenByClass(PlSqlParser.IdentifierContext.class)
                            .streamChildrenByClass(PlSqlParser.Id_expressionContext.class)
                            .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
                            .filter(TerminalNode.class::isInstance)
                            .toList());
                    if (returnValue.isEmpty()) {
                      returnValue.addAll(
                          ParseTreeStream.parseTreeStream(ctx)
                              .streamChildrenByClass(PlSqlParser.Foreign_key_clauseContext.class)
                              .streamChildrenByClass(PlSqlParser.Paren_column_listContext.class)
                              .streamChildrenByClass(PlSqlParser.Column_listContext.class)
                              .streamChildrenByClass(PlSqlParser.Column_nameContext.class)
                              .streamChildrenByClass(PlSqlParser.IdentifierContext.class)
                              .streamChildrenByClass(PlSqlParser.Id_expressionContext.class)
                              .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
                              .listAllTerminalNode()
                              .stream()
                              .toList());
                    }
                  }
                  return returnValue;
                })
            .flatMap(List::stream)
            .collect(Collectors.toCollection(ArrayList::new)));

    if (!terminalNode.isEmpty()) {
      return ParseTreeHelper.getRelationship(
          currentTable, String.join("_", terminalNode.stream().map(ParseTree::getText).toList()));
    }
    return null;
  }

  private SqlContext getCurrentTable(final ParserRuleContext ctx) {
    final var methodName = "getCurrentTable";
    PlSqlParserListenerImpl.traceChildren(methodName, ctx);

    if (ctx == null || ctx.children == null || ctx.children.isEmpty()) {
      return null;
    }

    final var parentContext =
        ParseTreeHelper.getParentContext(ctx, PlSqlParser.Create_tableContext.class);
    if (parentContext == null || parentContext.children == null) {
      return null;
    }

    var idExpressionChildrenList =
        ParseTreeStream.parseTreeStream(parentContext)
            .streamChildrenByClass(PlSqlParser.Schema_nameContext.class)
            .streamChildrenByClass(PlSqlParser.IdentifierContext.class)
            .listChildrenByClass(PlSqlParser.Id_expressionContext.class);

    final var terminalNodeTextList =
        ParseTreeStream.parseTreeStream(idExpressionChildrenList)
            .streamTerminalNodeString()
            .collect(Collectors.toList());

    terminalNodeTextList.addAll(
        ParseTreeStream.parseTreeStream(idExpressionChildrenList)
            .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
            .streamTerminalNodeString()
            .toList());

    idExpressionChildrenList =
        ParseTreeStream.parseTreeStream(parentContext)
            .streamChildrenByClass(PlSqlParser.Table_nameContext.class)
            .streamChildrenByClass(PlSqlParser.IdentifierContext.class)
            .listChildrenByClass(PlSqlParser.Id_expressionContext.class);

    terminalNodeTextList.addAll(
        ParseTreeStream.parseTreeStream(idExpressionChildrenList)
            .streamTerminalNodeString()
            .toList());
    terminalNodeTextList.addAll(
        ParseTreeStream.parseTreeStream(idExpressionChildrenList)
            .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
            .streamTerminalNodeString()
            .toList());
    terminalNodeTextList.addAll(
        ParseTreeStream.parseTreeStream(idExpressionChildrenList)
            .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
            .streamChildrenByClass(PlSqlParser.Non_reserved_keywords_pre12cContext.class)
            .streamTerminalNodeString()
            .toList());
    terminalNodeTextList.addAll(
        ParseTreeStream.parseTreeStream(idExpressionChildrenList)
            .streamChildrenByClass(PlSqlParser.Regular_idContext.class)
            .streamChildrenByClass(PlSqlParser.Non_reserved_keywords_in_12cContext.class)
            .streamTerminalNodeString()
            .toList());

    return SqlContextImpl.getInstance(this.getRootContext(), terminalNodeTextList);
  }

  /**
   * {@inheritDoc}
   *
   * @return a instance of the context.
   */
  @Override
  public SqlRootContext getRootContext() {
    if (this.rootContext == null) {
      this.rootContext = new SqlRootContextImpl();
    }
    return this.rootContext;
  }

  /**
   * {@inheritDoc}
   *
   * <p>The default implementation does nothing.
   */
  @Override
  public void visitTerminal(final TerminalNode node) {
    final var methodName = "visitTerminal";
    PlSqlParserListenerImpl.traceChildren(methodName, node);

    PlSqlParserListenerImpl.input = node.getSymbol().getInputStream();
  }
}
